name: Nim

on:
  push:
    branches:
    - master
    paths:
    - 'nim/**'
    - '.github/workflows/nim.yml'
    - '.github/workflows/common.yml'
  pull_request:
    paths:
    - 'nim/**'
    - '.github/workflows/nim.yml'
    - '.github/workflows/common.yml'
  workflow_dispatch:

jobs:
  common:
    name: Common
    uses: ./.github/workflows/common.yml
    with:
      workdir: nim
      with-nim: stable
      build-pkgs: libsdl2-dev
